name: Issue Content Generator

on:
  issues:
    types: [closed]

jobs:
  generate-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Generate file from issue
        run: node src/generateFile.js "${{ github.event.issue.html_url }}" "${{ github.event.issue.title }}" "${{ github.event.issue.body }}" "${{ github.event.issue.labels }}"


      - name: Commit and push changes
        env:
          TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        run: |
          echo "🔐 Remotely setting origin with token"
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}
          git remote -v  # Verifica que el token esté en la URL
          git add .
          git commit -m "chore: add file generated from issue #${{ github.event.issue.number }}" || echo "⚠️ No changes to commit"
          git push origin HEAD

